#!/usr/bin/env bash
# Function to get DNS information for a subdomain
# Usage: ./1-world_wide_web <domain> <subdomain>

domain_information () {
    # Execute a DNS lookup for the subdomain within the given domain.
    line=$(dig "$2", "$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    # Retrieve pertinent information and display it.
    echo "$2 $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

# Check if both arguments are provided to the script
if [ "$#" == 1 ]
then
    domain_information "$1" "www"
    domain_information "$1" "lb-01"
    domain_information "$1" "web-01"
    domain_information "$1" "web-02"
elif [ "$#" == 2 ]
then
    # if there are two argumemts, call the domain infomation
    domain_information "$1" "$2"
fi
