#!/usr/bin/env bash
# Install nginx
apt-get update
apt-get install -y nginx

# create dorectory and file with content Hello World!
mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html

# Make sure Nginx is listening on port 80
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;
}
" > /etc/nginx/sites-available/default

# Restarts the Nginx service to apply the configuration changes.
service nginx start
