#!/usr/bin/env bash
# Install nginx
apt-get update
apt-get install -y nginx

# Make sure Nginx is listening on port 80
sed -i 's/80 default_server/80 default_server;/g' /etc/nginx/sites-available/default

# Reload Nginx configuration to apply changes
nginx -s reload

# Create a page with "Hello World!"
echo "Hello World!" > /var/www/html/index.html

# Restarts the Nginx service to apply the configuration changes.
service nginx start
