#!/usr/bin/env bash
# Configures Nginx server so that /redirect_me redirects to another page
apt-get update
apt-get install -y nginx

# create dorectory and file with content Hello World!
mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html

# Make sure NGINX is listening on port 80
printf %s "server {
    listen      80 default_server;
    listen      [::]:80 default_server;
    root        /etc/nginx/html;
    index       index.html index.htm;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
" > /etc/nginx/sites-available/default

# Restart NGINX to apply changes
service nginx restart
