#!/usr/bin/env bash
# Check if Nginx is installed
if ! command -v nginx &>/dev/null; then
    echo "Nginx is not installed. Installing Nginx..."
    
    # Install Nginx
    apt-get update
    apt-get install -y nginx

    # Check if installation was successful
    if [ $? -ne 0 ]; then
        echo "Failed to install Nginx. Exiting."
        exit 1
    fi
fi

# Set up redirection in Nginx configuration
REDIRECT_CONFIG="location /redirect_me {
    return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
}"

echo "$REDIRECT_CONFIG" | tee -a /etc/nginx/sites-available/default >/dev/null

# Reload Nginx configuration to apply changes
nginx -s reload
