#!/usr/bin/env bash
# Configures Nginx server so that /redirect_me redirects to another page
# Configures /redirect_me as a "301 Moved Permanently".
# Includes a custom 404 page containing "Ceci n'est pas une page".
apt-get update
apt-get install -y nginx

# create dorectory and file with content Hello World!
mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html
touch /etc/nginx/html/404.html
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html

# Make sure Nginx is listening on port 80
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;

     location /redirect_me {
        return 301 http://cuberule.com/;
     }

     error_page 404 /404.html;
     location /404 {
	root /etc/nginx/html;
	internal;
     }
}
" > /etc/nginx/sites-available/default

# Restarts the Nginx service to apply the configuration changes.
service nginx start
