#!/usr/bin/env bash
# Configures Nginx server so that /redirect_me redirects to another page
# Configures /redirect_me as a "301 Moved Permanently".
# Includes a custom 404 page containing "Ceci n'est pas une page".
# Script to configure Nginx with a custom HTTP response header

apt-get update
apt-get install -y nginx

# create dorectory and file with content Hello World!
mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html

# Make sure Nginx is listening on port 80
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;

}
" > /etc/nginx/sites-available/default

#  creates an empty file named 404.html
touch /etc/nginx/html/404.html
echo "Ceci n'est pas une page" | sudo tee /etc/nginx/html/404.html

# Display script completion message
echo "Nginx installation and configuration completed."

# Create configuration file for the redirection.
echo "server {
    listen      80;
    listen      [::]:80;
    root        /etc/nginx/html;
    index       index.html index.htm;

    # Add index.php to the list if you are using PHP
    index index.html index.htm index.nginx-debian.html;

    location /redirect_me {
       return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    error_page 404 /404.html;
    location /404 {
	root /etc/nginx/html;
	internal;
    }

}" | sudo tee /etc/nginx/sites-available/default

# Enable the new site configuration
sudo ln -s "server_name _;/a add_hearder X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default

# Test nginx configuration and reload
sudo nginx -t

# Restarts the Nginx service to apply the configuration changes.
sudo service nginx reload
