#!/usr/bin/env bash
# This script performs various actions based on signals.

# Define signal handlers
function handle_sigterm {
    echo "I hate the kill command"
    cleanup_and_exit
}

function handle_sigint {
    echo "Y U no love me?!"
    cleanup_and_exit
}

function cleanup_and_exit {
    rm /var/run/myscript.pid
    exit 0
}

# Set signal handlers
trap handle_sigterm SIGTERM
trap handle_sigint SIGINT

# Create PID file
echo $$ > /var/run/myscript.pid

# Main loop
while true; do
    echo "To infinity and beyond indefinitely"
    sleep 2
done
