#!/usr/bin/env bash
# This script displays username, user id, and home directory path for each user in /etc/passwd.

while read -r passwd; do
  echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
