#!/usr/bin/env bash
# This script creates a story based on /etc/passwd file.

while IFS=: read -r username _ uid gid gecos home shell; do
    echo "The user $username is part of the group $gid gang, lives in $home and rides $shell."
    echo "User ID's place is protected by the passcode $(sudo grep -E "^$username:" /etc/shadow | cut -d: -f2), more info about the user here: $gecos"
    echo
done < /etc/passwd
