#!/usr/bin/env bash
# This script displays the time in 12-hour format.

hours=0

while [ $hours -le 12 ]; do
    minutes=1
    while [ $minutes -le 59 ]; do
	if [ $minutes -eq 1 ]; then
            echo "Hour: $hours"

	fi        
        echo "$minutes"
        ((minutes++))
    done
    ((hours++))
done
