#!/usr/bin/env bash
# This script displays the content of the current directory in a specific format.

for file in *; do
    if [ -f "$file" ] && [[ "$file" != .* ]]; then
        name=$(echo "$file" | cut -d'-' -f2-)
        echo "$name"
    fi
done
